### ISSUE TITLE
dynamic removal result between octomap and dufomap

### ISSUE THREAD

**Issue by sanduan168** [KTH-RPL/dufomap#4]
Hi Qing Wen
I test dufomap and octomap with my dataset.
![图片](https://github.com/KTH-RPL/dufomap/assets/15241266/3b02448a-2d76-47b6-8b1e-0b4e15dd92f7)
The result above is from dufomap with the default config.toml. We can see that some dynamic objects(in red circle) are not trimmed.
The result below is from octomap(https://github.com/Kin-Zhang/octomap.git) with default config.yml. Even though the static objects(in green rectangle) are removed, the dynamic objects are almost deleted.
![图片](https://github.com/KTH-RPL/dufomap/assets/15241266/fbb7d0ad-84d9-4a0c-8acc-ad68a644ff2a)
In your paper, the SA\DA of dufomap performs better than octomap, which is inconsistent with my experiment. Can you explain why? 
If you want to reproduce, you can download the dataset from: https://drive.google.com/drive/folders/1kpevt1zkFlDNiw-h6ISCD13-W8EdX6By?usp=drive_link

**Comment by Kin-Zhang** [comment]
Hi,

the dataset link download is not available. Please give full access: You need access.

hard to tell if I cannot open the data you provided, the conclusion we summarise is based on experiments of existing datasets, when changing datasets/scenarios, the statement from the previous may need to change. That's why all papers will say: based on xxx dataset, we have xxx conclusion. or existing experiment on xxx dataset.

**Comment by sanduan168** [comment]
the following link is available:
https://drive.google.com/drive/folders/1kpevt1zkFlDNiw-h6ISCD13-W8EdX6By?usp=sharing

**Comment by qimao7213** [comment]
你可以把assert里面的配置文件、resolution调成0.2，然后把ray_passthrough_hits设置为true试试呢。
