### ISSUE TITLE
Is there a version that can run on windows?

### ISSUE THREAD

**Issue by DGCHAO** [KTH-RPL/dufomap#7]
This works great, I want to run it on windows, but I have some problems? Is there a windows version?

**Comment by DGCHAO** [comment]
> I think you can compile in Windows but need to figure out the compile tool and option by yourself. I didn't try it on Windows, but I tried it on WLS2 and it works.

I will give it a try, thanks!

**Comment by Rogers34** [comment]
Hi @Kin-Zhang @DGCHAO ,
Hello, have you successfully compiled this code on Windows VS2019? I also encountered some issues during the compilation

**Comment by DGCHAO** [comment]
> Hi @Kin-Zhang @DGCHAO , Hello, have you successfully compiled this code on Windows VS2019? I also encountered some issues during the compilation

Yes, some modifications have been made to small parts of the code.

**Comment by zuixiaosanlang** [comment]
@DGCHAO @Kin-Zhang @Rogers34 
hello, 
build on windows, 
error: constexpr 函数“ufo::Frustum::Frustum”不能生成常量表达式

how to solve such error ??

thanks.

i notice my c++ version:  ISO C++20 标准 (/std:c++20)

![image](https://github.com/user-attachments/assets/98ce8c7c-1ba0-4522-af9d-460b2b19ffb3)

![image](https://github.com/user-attachments/assets/7daa9d22-d799-4d4d-9b93-5def95494640)

**Comment by Kin-Zhang** [comment]
> @DGCHAO @Kin-Zhang @Rogers34 hello, build on windows, error: constexpr 函数“ufo::Frustum::Frustum”不能生成常量表达式
> 
> how to solve such error ??
> 
> thanks.

The reason is Window's compiler (MSVC) is different with GCC/Clang, some rules on constexpr might be stricter. A quick fix could be:
option A: removing constexpr (if it's in the class)
option B: change `constexpr` function to `inline`

But I don't think it's the only error will occur in Windows, I will soon update a python package (hopefully before Nov.), which is available in both Windows and Ubuntu, timetable in Windows: https://github.com/Kin-Zhang/dufomap/discussions/1#discussioncomment-10495188
